---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: src/pages/index.js
  label: Index
upload_dir: https://github.com/Robert95Sch/brauerei-website/tree/master/src/assets/images
public_path: https://github.com/Robert95Sch/brauerei-website/tree/master/src/assets/images
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
