name: Buildwith-IONOS

on: [push]

jobs:
  build-with-ionos:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Get Ionos Project data
        uses: buildwith-ionos/retrieve-project-info-action@v0.1.2
        id: project
        with:
          project: 04f1e97e-6a2d-4e71-bed0-9258c816b3ef
          api-key: ${{ secrets.IONOS_API_KEY }}
      - name: Setup Node.js 12.16.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.x
      - name: Prepare Project build environment
        run: npm install
      - name: Build Node project
        run: npm run build
        env:
          SITE_URL: ${{ steps.project.outputs.site-url }}
          CI: true
      - name: Deploy to IONOS
        uses: buildwith-ionos/deploy-to-ionos-action@v0.1.2
        with:
          remote-host: ${{ steps.project.outputs.remote-host }}
          dist-folder: public
          api-key: ${{ secrets.IONOS_API_KEY }}
          project: 04f1e97e-6a2d-4e71-bed0-9258c816b3ef
